### ISSUE TITLE
Understand the data sources for budget lines

### ISSUE THREAD

**Issue by carjug** [18F/OPRE-Unicorn#41]
Budget line data is displayed in multiple places in MAPS.  We want to understand where the data is being pulled from to help us understand if there might be discrepancies and to ultimately inform how we want to pull/display budget line data in Unicorn.

**Places that budget line data appear in MAPS**
* All Budget grid
* Contracts page: 3 tabs at the bottom (Budget Lines, Pre-Award Tracking, Post-Award Tracking
* Grants page: 1 tab
* IAA page: 1 tab
* DIrect Obligation page: 1 tab

**Tasks**

- [x] Document the sources of the budget line data above, inc any joins.

**Comment by ninamak** [comment]
@amymok I updated this card with work that I would find useful.  Is there anything you'd add to this scope?  

If this ends up being approximately the scope, I'm thinking we should bring this into the cycle since you've already started it, and focus on closing it out.  Which largely means moving the documentation out of Slack (maybe you've done that already?), and checking the Grant, IAA, and Direct Obligation tabs (which are expected to be just like the Contract tabs).

If the scope ends up much larger, then we should at least update the tasks that have already been completed (or could easily be completed, like moving documentation from Slack into something more durable).

What do you think?

**Comment by amymok** [comment]
@ninamak, the detail you added is very helpful.  Right now the work is mostly in my notes, and the summary is on Slack.  I only focused on the 3 tabs.  I am thinking we may want to document this along side the [Database folder](https://drive.google.com/drive/folders/1stDcnEyB9bnYh4V_0CXeS7-P9V5sxfEL).  Maybe I will start a MAPS 1.0 Documentation folder and move the database in this folder and add a document for this work?  Thoughts?

Yes we can move it in to at least finish up the work that we have done.

**Comment by ninamak** [comment]
@amymok That plan sounds good to me!  Thank you!

**Comment by amymok** [comment]
Moved [Database folder](https://drive.google.com/drive/folders/1stDcnEyB9bnYh4V_0CXeS7-P9V5sxfEL?usp=sharing) in [MAPS 1.0 Documentation folder](https://drive.google.com/drive/folders/1QtoBkqqEKSkrMS9AiqTXEUzRNlHjP6Wn).

Pulled out conversation about contracts page 3 tabs in the [Data Sources for Budget Lines doc](https://docs.google.com/document/d/1I9JMAaGXxpD8bII1zevTvv8u60z4zDfvu4-0_zjZuo8/edit#) in [MAPS 1.0 Documentation folder](https://drive.google.com/drive/folders/1QtoBkqqEKSkrMS9AiqTXEUzRNlHjP6Wn).

**Comment by amymok** [comment]
@ninamak Please take a look at the [Data Sources doc](https://docs.google.com/document/d/1I9JMAaGXxpD8bII1zevTvv8u60z4zDfvu4-0_zjZuo8/edit#), and let me know if you have any questions on any of them.

**Comment by ninamak** [comment]
@amymok Thank you!  This looks good to me.  I left one comment on the doc, to see if it's worth digging into the sources of the AllBudget view.

**Comment by ninamak** [comment]
@amymok The documentation on the AllBudget view is perfect, thank you!  I'm all good to close this one out if you are!
