### ISSUE TITLE
[Spike] Investigate feasibility of moving repo to HHS GH

### ISSUE THREAD

**Issue by ninamak** [18F/OPRE-Unicorn#84]
### Goals
* Determine if there are any tools we want to use that we don't have approval to use in HHS GH so that we can determine when to migrate from our 18F GH repo to HHS.

### Tasks
- [ ] @alexsoble Can you help identify the tasks that would go into this investigation?

### Additional Context
* We are currently using a public 18F GH repo, but will ultimately want to move this into HHS control.  We feel confident we can use a public HHS GH repo (thus avoiding the limitation they have with licenses), but we do not know if there are any tools we'd like to use that we don't have access to / will need to work to gain access to.

### Resources
* _Links to useful related info (e.g., articles, help docs, etc)_

**Comment by alexsoble** [comment]
Hmmmmmm, we've already been researching & discussing this in #36 and #55 and on Slack. I don't think there's a whole lot of additional work to do here. 

* We decided we'd like to use HHS CircleCI for CI/CD, that's not a GitHub tool
* We know GitHub Dependabot is available in HHS GitHub because TTA SmartHub is using it, right now
* We may want to use GitHub CodeQL for static analysis but if for some reason that's not available on HHS GitHub, we can ask HHS what alternative tools are approved/recommended 

I can see from the TTA SmartHub repo that Project Boards are available in the HHS GitHub as well: https://github.com/HHS/Head-Start-TTADP/projects/1

@amymok @carjug @ninamak Any other GitHub tools or services you can think of that we would want to think about or investigate here?

**Comment by ninamak** [comment]
Won't Do.

Per team: we know we will need to move to HHS GH eventually, so it would be better to do that right away and find out if there are any planned tools that we couldn't use so that we can decide on an alternative and avoid investing in building a thing we'll have to replace.
